---
disable_EE_options: False # broken with 19, fix is not merged yet
apply_patches_db: True # enable db patching


db_homes_config:
  19300-base:
    home: db1
    version: 19.3.0.0
    edition: EE
    # patch this home
    opatch_minversion: 12.2.0.1.19 # non optional, should be in patch config
    opatchauto: [] # opatchauto (with GI) & opatch is needed, wether used or not
    opatch:
    - patchid: 31771877
      stop_processes: true
      state: present

  11204-base:
    home: db1
    version: 11.2.0.4
    edition: EE

db_homes_installed:
        - home: 19300-base
          # apply_patches: False
          apply_patches: True
          # opatchauto:
          # - patchid: RU_19.9
          #   stop_processes: true
          #   state: present
          state: present
        - home: 11204-base
          apply_patches: false
          state: present
