---
disable_EE_options: False

db_homes_config:
  19300-base:
    home: db1
    version: 19.3.0.0
    edition: EE
    opatchauto:
    - patchid: RU_19.9
      stop_processes: true
      state: present
    # patch this home

  11204-base:
    home: db1
    version: 11.2.0.4
    edition: EE

db_homes_installed:
        - home: 19300-base
          # apply_patches: False
          apply_patches: True
          opatchauto:
          - patchid: RU_19.9
            stop_processes: true
            state: present
          state: present
        - home: 11204-base
          apply_patches: false
          state: present
