---
oracle_tnsnames_config:
  TEST:
    address:
    - host: orahost01
    - host: orahost02
      port: 1522
    connect_timeout: 10
    transport_connect_timeout: 6
    retry_count: 10
    connect:
      sid_name: TEST
  cdb19:
    address:
    - host:
    # connect:
    #   service_name: TEST_RW
  TESTDG:
    tnstemplate: dgfailover2
    address:
    - host: orahost01
    - host: orahost02
    connect:
      service_name: TEST_RW

tnsnames_installed:
  - home: 19300-base
    tnsname: TEST
  - home: 19300-base
    tnsname: TESTDG
  - home: 19300-base
    tnsname: cdb19
  - home: 11204-base
    tnsname: TEST
